version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bd-biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db  # ¡Este es el nombre del servicio, no localhost!
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: bd-biblioteca
      POSTGRES_SSL: false
      JWT_SECRET: 987654321
      MONGO_URI: mongodb+srv://ijalvarez:NY8ycD3BB4GQ7jwK@cluster0.gwreou4.mongodb.net/logs_biblioteca?retryWrites=true&w=majority

volumes:
  pgdata:

#docker-compose up --build